FROM public.ecr.aws/lambda/python:3.12

# Dependências do scraper
COPY requirements.txt ${LAMBDA_TASK_ROOT}/
RUN pip install --no-cache-dir -r ${LAMBDA_TASK_ROOT}/requirements.txt

# Código da Lambda
COPY scraper.py ${LAMBDA_TASK_ROOT}/

CMD ["scraper.handler"]
